DROP DATABASE IF EXISTS `shelter_bd`;
#CREATE SCHEMA IF NOT EXISTS `shelter_bd` DEFAULT CHARACTER SET utf8 ;
CREATE DATABASE `shelter_bd`;
USE `shelter_bd` ;

CREATE TABLE USER (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(11),
  `email` VARCHAR(45),
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CHECK(`phone` IS NOT NULL || `email` is NOT NULL))
DEFAULT CHARACTER SET = utf8;

CREATE TABLE HUMAN (
  `id` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) DEFAULT NULL,
  `birthdate` DATE DEFAULT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id`) REFERENCES USER (`id`)
    ON DELETE CASCADE)
DEFAULT CHARACTER SET = utf8;


CREATE TABLE ORGANISATION (
  `id` INT(11) NOT NULL,
  `TIN` VARCHAR(12) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `additionalInfo` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `TIN_UNIQUE` (`TIN` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  FOREIGN KEY (`id`) REFERENCES USER (`id`)
    ON DELETE CASCADE)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE ANIMAL_TYPE (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
#ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE ANIMAL (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT(3)DEFAULT NULL,
  `sex` ENUM ('F','M') NOT NULL,
 #`idCategory` INT(11) NOT NULL,
  `breed` VARCHAR(45) DEFAULT NULL,
  `idAnimalType` INT(11) NOT NULL,
  `passport` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `passport_UNIQUE` (`passport` ASC),
  FOREIGN KEY (`idAnimalType`) REFERENCES ANIMAL_TYPE (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


CREATE TABLE CATEGORY(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
DEFAULT CHARACTER SET = utf8;


CREATE TABLE CARD (
  `idAnimal` INT(11) NOT NULL,
  `idUser` INT(11) NOT NULL,
  `idCategory` INT(11) NOT NULL,
  `body` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`idAnimal`, `idUser`),
  FOREIGN KEY (`idAnimal`) REFERENCES ANIMAL (`id`)
    ON DELETE CASCADE,
  FOREIGN KEY (`idCategory`) REFERENCES CATEGORY (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`idUser`) REFERENCES USER (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
#ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
